### ISSUE TITLE
AttributeError: 'Response' object has no attribute '_resource_closers' in production logs

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/contratospr-api#143]
**Describe the bug**
We've been seeing the following error appear in our production logs but not our tests:

```
2020-06-29T16:13:45.612999+00:00 app[web.1]: [2020-06-29 16:13:45 +0000] [13] [ERROR] Error handling request /v1/contracts/2020-000028-4969339/
2020-06-29T16:13:45.613046+00:00 app[web.1]: Traceback (most recent call last):
2020-06-29T16:13:45.613048+00:00 app[web.1]: File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 134, in handle
2020-06-29T16:13:45.613049+00:00 app[web.1]: self.handle_request(listener, req, client, addr)
2020-06-29T16:13:45.613057+00:00 app[web.1]: File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
2020-06-29T16:13:45.613058+00:00 app[web.1]: respiter = self.wsgi(environ, resp.start_response)
2020-06-29T16:13:45.613058+00:00 app[web.1]: File "/usr/local/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
2020-06-29T16:13:45.613058+00:00 app[web.1]: response = self.get_response(request)
2020-06-29T16:13:45.613059+00:00 app[web.1]: File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 76, in get_response
2020-06-29T16:13:45.613059+00:00 app[web.1]: response._resource_closers.append(request.close)
2020-06-29T16:13:45.613060+00:00 app[web.1]: AttributeError: 'Response' object has no attribute '_resource_closers'
```
Up to now we don't know the reason but will be looking into it.

----

CC @jpadilla

**Comment by braunly** [comment]
+1 here

**Comment by froi** [comment]
Hi @braunly 👋🏼 

Are you interested in working on this??? I'd have to revisit it, it's been a while 😅.
